### ISSUE TITLE
How to name a palette of a big city group

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#21]
I would like to update a color palette of a city group, which is combined with 6 cities: Essen, Mülheim, Oberhausen, Bochum, Gelsenkirchen and Herne, whose tram and light rail system are tied together. The system of Bochum, Gelsenkirchen and Herne belongs to BOGESTRA, but the system of Essen, Mülheim and Oberhausen belongs to RUHRBAHN. I would like to know how to decide the name of the palette. I might choose both of the official sites for the txt.

**Comment by thekingofcity** [comment]
I think we don't have a convention on how to handle this situation. You may use any format to split/merge them.

- Essen, Mülheim, Oberhausen, Bochum, Gelsenkirchen and Herne
- BOGESTRA, RUHRBAHN (we typically don't display colors in companies but in geographical location, so better not this)
- The great xxx area
- Any other ways not mentioned above

Thanks for your contribution to places we never heard before 🤣

**Comment by linchen1965** [comment]
I think I'll name it "Rhein-Ruhr Gebiet", but I need to add another color palettes of Düsseldorf Duisburg Krefeld and Wuppertal. So it'll be a large project with 10 cities. By next update I'll also update color palettes of Berlin, Munich and Frankfurt

**Comment by wongchito** [comment]
Hi @linchen1965, 

After doing some research on Rhein-Ruhr, I have some suggestions on naming this metropolitan region:

1. English name: Rhein-Ruhr Metropolitan region
2. German name: Metropolregion Rhein-Ruhr
3. Chinese name: 萊茵-魯爾都會區
4. Filename/ID: rheinruhr

These follow the convention of naming Greater Tokyo Area and Seoul (Metropolitan Area). 

Please shout if you think this naming is ambiguous or is not accurate, otherwise we will use this as for #22 and there's no action for you. Thank you!
