### ISSUE TITLE
Resources: New palettes of Tokyo Metropolis

### ISSUE THREAD

**Issue by NYYTNYC** [railmapgen/rmg-palette#302]
**Justification:** from https://www.tokyometro.jp/station/202006_number_ja.pdf and https://www.kotsu.metro.tokyo.jp/subway/line.pdf 

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "tokyo",
    "country": "JP",
    "name": {
        "en": "Tokyo and Toei Metro",
        "ja": "東京メトロと都営地下鉄"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "g",
        "colour": "#f9a328",
        "fg": "#fff",
        "name": {
            "ja": "銀座線",
            "en": "Ginza Line"
        }
    },
    {
        "id": "m",
        "colour": "#ee2628",
        "fg": "#fff",
        "name": {
            "ja": "丸ノ内線",
            "en": "Marunouchi Line"
        }
    },
    {
        "id": "h",
        "colour": "#c7beb3",
        "fg": "#fff",
        "name": {
            "ja": "日比谷線",
            "en": "Hibiya Line"
        }
    },
    {
        "id": "t",
        "colour": "#00afef",
        "fg": "#fff",
        "name": {
            "ja": "東西線",
            "en": "Tozai Line"
        }
    },
    {
        "id": "c",
        "colour": "#1bb267",
        "fg": "#fff",
        "name": {
            "ja": "千代田線",
            "en": "Chiyoda Line"
        }
    },
    {
        "id": "y",
        "colour": "#d1a662",
        "fg": "#fff",
        "name": {
            "ja": "有楽町線",
            "en": "Yurakucho Line"
        }
    },
    {
        "id": "z",
        "colour": "#8c7dba",
        "fg": "#fff",
        "name": {
            "ja": "半蔵門線",
            "en": "Hanzomon Line"
        }
    },
    {
        "id": "n",
        "colour": "#02b69b",
        "fg": "#fff",
        "name": {
            "ja": "南北線",
            "en": "Namboku Line"
        }
    },
    {
        "id": "f",
        "colour": "#a95e33",
        "fg": "#fff",
        "name": {
            "ja": "副都心線",
            "en": "Fukutoshin Line"
        }
    },
    {
        "id": "a",
        "colour": "#ec6d65",
        "fg": "#fff",
        "name": {
            "ja": "浅草線",
            "en": "Asakusa Line"
        }
    },
    {
        "id": "i",
        "colour": "#006ab7",
        "fg": "#fff",
        "name": {
            "ja": "三田線",
            "en": "Mita Line"
        }
    },
    {
        "id": "s",
        "colour": "#7ab629",
        "fg": "#fff",
        "name": {
            "ja": "新宿線",
            "en": "Shinjuku Line"
        }
    },
    {
        "id": "o",
        "colour": "#da006e",
        "fg": "#fff",
        "name": {
            "ja": "大江戸線",
            "en": "Oedo Line"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我注意到您提供了两个线路颜色来源，而这两个来源中所给的线路系统相同但各线路颜色均有细微差别。因此我们无法确认您所提交的线路颜色是基于哪一个来源制作的。

此外，在咱们的颜色库已经包含东京都地铁的系统线路颜色，而由于你所提交的地区名与项目中现有内容并不相同，可能会导致项目中出现两个相同地区的错误状况。因此很抱歉，我们不会接受您的投稿。

如您想要修改当前项目中已有的东京都地铁颜色，您可以在https://railmapgen.github.io/rmg-palette 中找到东京都并点击列表最右侧的铅笔标识进行修改。

Hi, I just noticed that you submit two resources for your color palette, which both sources contains same metro lines but with different colors. Hence we cannot determine which one is the source you based on.

In addition, we already have Tokyo Metropolis line palette in the project, since your palette is named as "Tokyo and Toei Metro" but exactly is lines in Tokyo Metropolis, there will be the glitch that two color palette with different name but in same area if we merge it. Therefore, we are sorry that your palette will not be accepted.

此外，在您下次提交线路颜色前希望注意以下几点：
* 与线路模版不同，线路颜色是按照地区划分而非铁路系统划分的，所以请您下次提交线路颜色时不要在地区名中填入铁路线路名称。
* 虽然日语也被允许且建议在提交日本的线路颜色时写上，但由于本项目主要支持语言为以中国大陆地区翻译为准的简体中文，以香港地区翻译为准的繁体中文和英文，因此希望在下次提交线路颜色时补充上地区和各线路的简体与繁体中文名。

Additionally, please notice following suggestion before your next color palette submission:
* Unlike line templates, the color palette is based on the cities and areas, not transit system, so please do not write system name like "Tokyo and Toei Metro" in city section.
* Since the Rail Map Generator only support to display Simplified Chinese based on Mainland China translation, Traditional Chinese based on Hong Kong translation and English, please add both Simplified and Traditional Chinese name to your palette although Japanese is allow and recommend to put into color palette for Japan railway lines.
